OPTION DIALECT MODERN
OPTION CPUSPEED MAX
REM***A PRIME NUMBER SIEVE BENCHMARK
T = TIMER
C = 0
N = 8191
DIM F(N+1)
FOR I = 0 TO N : F(I)=1 : NEXT I
S = N
FOR I = 0 TO S
   IF F(I)=0 THEN GOTO skip ELSE P = I+I+3
   IF I+P>S THEN GOTO skip
   FOR K=I+P TO S STEP P : F(K)=0 : NEXT K
   C = C+1
Skip: NEXT
T = TIMER-T
PRINT C;" PRIMES FOUND IN ";T;" SECONDS"
END
